added select with country filter and updated courses page
Vj3ko/assignment pull request #5
Opened 2023-08-31 11:02 UTC by Vj3ko

2023-09-05 20:44 UTC, kosbreiev commented on next_task/app/(company)/courses/fullstack/page.jsx
>          <div style={{ display: "flex", gap: 40 }}>
Try to avoid mixing inline styles with the scss file.  Consider moving these to your SCSS modules for better maintainability

2023-09-05 20:46 UTC, kosbreiev commented on next_task/app/(company)/courses/fullstack/page.jsx
> +async function getCountries() {
there is no catch block in the code to handle the error.

2023-09-05 21:15 UTC, kosbreiev requested changes

2023-09-05 21:15 UTC, kosbreiev commented on next_task/components/countrySelector/countrySelector.jsx
> +const countrySelector = ({ countries }) => {
CountrySelector

2023-09-05 21:15 UTC, kosbreiev commented on next_task/components/countrySelector/countrySelector.jsx
> +    const filtered = countries.filter(
Data structure of the selected should be consistent:
const filter = (item) => {
  const filtered = countries.find(country => country.name.common === item);
  setSelected(filtered);
};

2023-09-05 21:15 UTC, kosbreiev commented on next_task/components/countrySelector/countrySelector.jsx
> +  const sortCountries = (a, b) => {
Consider moving this function outside of the component so that it doesn't get recreated on every render.

2023-09-05 21:15 UTC, kosbreiev commented on next_task/components/countrySelector/countrySelector.jsx
> +          <Image
Consider adding error handling or a placeholder image if the flag can't be loaded.

2023-09-05 21:15 UTC, kosbreiev commented on next_task/components/countrySelector/countrySelector.jsx
> +export default countrySelector;
Add PropTypes to enforce the data types of the props and add default props to handle any missing props.
We will switch soon to TS, but its a good practice to add PropTypes

2023-09-05 21:15 UTC, kosbreiev commented on next_task/components/countrySelector/countrySelector.module.scss
> +.countries {
General suggestions:
1) use vars
$primary-color: #777;
$secondary-color: rgba(128, 128, 128, 0.2);
$padding-horizontal: 10px;
2)  Consider using relative units like em or rem instead of px.
3) Accessible Focus
4) Add comments

2023-09-05 21:15 UTC, kosbreiev commented on next_task/components/dropdown/dropdown.jsx
> +"use client";
Use ARIA roles/attributes. Read about this

2023-09-05 21:15 UTC, kosbreiev commented on next_task/components/dropdown/dropdown.jsx
> +const Dropdown = ({ title }) => {
If the dropdown lists get too long, consider adding some form of virtualization or pagination.

2023-09-05 21:15 UTC, kosbreiev commented on next_task/components/dropdown/dropdown.jsx
> +export default Dropdown;
PropTypes

2023-09-06 08:32 UTC, Vj3ko commented on next_task/app/(company)/courses/fullstack/page.jsx
> +const Consultation = async () => {
moved fetching to countries component itself using SWR

2023-09-06 08:34 UTC, Vj3ko commented on next_task/app/(company)/courses/fullstack/page.jsx
> +          <CurriculumItem item={curr} key={curr.title + index} />
was using this just until we get actual fetch from some API and guessing there will be ID, but for now i installed nanoid package and used that for keys

2023-09-06 08:47 UTC, Vj3ko commented on next_task/app/(company)/courses/fullstack/page.jsx
>          <div style={{ display: "flex", gap: 40 }}>
removed, and fixed inline styling

2023-09-06 08:47 UTC, Vj3ko commented on next_task/app/(company)/courses/fullstack/page.jsx
> +          <div style={{ flex: 1.5, position: "relative" }}>
removed

2023-09-06 09:30 UTC, Vj3ko commented on next_task/app/(home)/page.jsx
> +            width={515}
removed numbers, and surrounded image component with a wrapper div, and set width and height to that div in css

2023-09-07 08:24 UTC, merged

2023-09-07 09:58 UTC, Vj3ko commented on next_task/components/countrySelector/countrySelector.jsx
> +    const filtered = countries.filter(
that was prettier extension doing its thing but i added config file to fix it

2023-09-07 10:34 UTC, Vj3ko commented on next_task/components/countrySelector/countrySelector.jsx
> +          <Image
implemented

2023-09-07 10:35 UTC, Vj3ko commented on next_task/components/countrySelector/countrySelector.jsx
> +  const sortCountries = (a, b) => {
moved outside.

2023-09-07 10:51 UTC, Vj3ko commented on next_task/components/dropdown/dropdown.jsx
> +export default Dropdown;
implemented

2023-09-07 10:58 UTC, Vj3ko commented on next_task/components/countrySelector/countrySelector.jsx
> +export default countrySelector;
implemented